[#268 ] RABC authentication feature
huaweicloud/spring-cloud-huawei pull request #269
Opened 2020-10-15 07:05 UTC by GuoYL123

2020-10-16 02:11 UTC, tianxiaoliang requested changes

2020-10-16 02:11 UTC, tianxiaoliang commented on spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombWatcher.java
> +      signedHeader.put("Authorization", "Bearer " + TokenCache.getToken().getToken());
TokenCache.getToken().getToken()写法不太好，概念重叠

2020-10-16 02:11 UTC, tianxiaoliang commented on spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/DefaultHttpTransport.java
> +        if (response.getStatusCode() == 200) {
200 能否用常量

2020-10-20 03:53 UTC, GuoYL123 commented on spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombWatcher.java
> +      signedHeader.put("Authorization", "Bearer " + TokenCache.getToken().getToken());
done

2020-10-20 03:53 UTC, GuoYL123 commented on spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/DefaultHttpTransport.java
> +        if (response.getStatusCode() == 200) {
done

2020-10-21 02:00 UTC, merged