[#267 ] add governance feature
huaweicloud/spring-cloud-huawei pull request #272
Opened 2020-10-21 02:21 UTC by GuoYL123

2020-10-21 02:42 UTC, tianxiaoliang requested changes

2020-10-21 02:42 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/README.md
> +在实现过程中，定义一套interface和spec，叫做：servicecomb runtime interface ( SCRI )，基于
基于 改为 默认实现基于

2020-10-21 02:42 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/minimized-demo/consumer-demo/src/main/resources/application.yaml
> +        traffic-to-some-api-from-jack: |
name改下，贴近描述的意思

2020-10-21 02:42 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/minimized-demo/consumer-demo/src/main/resources/application.yaml
> +          timeoutDuration: 25
这些配置项具体什么意思，另外时间类，都要加单位，代码再做解析，比如1s 2h

2020-10-21 02:42 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/service/PolicyService.java
> +  Policy getCircuitBreakerPolicy(String mark);
再加个接口 getCustomPolicy(string kind, string mark)

2020-10-21 02:49 UTC, tianxiaoliang requested changes

2020-10-21 02:49 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/service/PolicyServiceImpl.java
> +      policyResult = ratePolicies.get("global");
global 应该是none，另外抽个常量

2020-10-21 02:49 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/service/PolicyServiceImpl.java
> +    for (Entry<String, RateLimitingPolicy> entry : ratePolicies.entrySet()) {
直接map get不就行了 ratePolicies 的key并不是name而是mark的名字，提前索引好

2020-10-21 03:01 UTC, tianxiaoliang requested changes

2020-10-21 03:01 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/handler/RateLimitingHandler.java
> + * 每隔limitRefreshPeriod的时间会加入limitForPeriod个新许可
太复杂了，用户就需要定义限流，不需要理解算法，实现细节，可以作为高级配置提供

2020-10-21 07:01 UTC, GuoYL123 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/service/PolicyServiceImpl.java
> +    for (Entry<String, RateLimitingPolicy> entry : ratePolicies.entrySet()) {
这样做并不好，
表面上看：当前遍历查找复杂度是O(n)；如果我们维护mark -> List<Policy>，复杂度会降低到O(1)。
原因是：
我们需要在请求到来前建立mark -> List<Policy>这样的关系缓存。但是由于我们需要响应动态配置的变更，所以实际上每次请求都要去进行一个重新建立关系缓存的refresh行为，这样的话时间复杂度没有降低，反而增加了代码复杂性和空间消耗。

2020-10-21 07:17 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/handler/RateLimitingHandler.java
> + * 每隔limitRefreshPeriod的时间会加入limitForPeriod个新许可
代码保留 新增个字段 rate 就是表示每秒接多少请求

2020-10-21 09:12 UTC, GuoYL123 commented on spring-cloud-huawei-governance/README.md
> +在实现过程中，定义一套interface和spec，叫做：servicecomb runtime interface ( SCRI )，基于
done

2020-10-21 09:12 UTC, GuoYL123 commented on spring-cloud-huawei-sample/minimized-demo/consumer-demo/src/main/resources/application.yaml
> +        traffic-to-some-api-from-jack: |
done

2020-10-21 09:12 UTC, GuoYL123 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/service/PolicyService.java
> +  Policy getCircuitBreakerPolicy(String mark);
done

2020-10-21 09:14 UTC, GuoYL123 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/service/PolicyServiceImpl.java
> +      policyResult = ratePolicies.get("global");
done

2020-10-21 09:14 UTC, GuoYL123 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/properties/SerializeCache.java
> +        e.printStackTrace();
done

2020-10-21 09:14 UTC, GuoYL123 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/properties/MatchProperties.java
> +@ConfigurationProperties("spring.cloud.servicecomb")
done

2020-10-21 09:19 UTC, GuoYL123 commented on spring-cloud-huawei-sample/minimized-demo/consumer-demo/src/main/resources/application.yaml
> +          timeoutDuration: 25
当前是默认为ms

2020-10-22 08:38 UTC, little-cui requested changes

2020-10-23 02:05 UTC, GuoYL123 commented on spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/exception/IllegalArgsOperator.java
> +public class IllegalArgsOperator extends ServiceCombRuntimeException {
done

2020-10-23 08:06 UTC, merged