governance add retry
huaweicloud/spring-cloud-huawei pull request #275
Opened 2020-10-27 08:37 UTC by GuoYL123

2020-10-27 10:13 UTC, tianxiaoliang requested changes

2020-10-27 10:13 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/governance-demo/consumer/src/main/resources/application.yaml
> +      maxAttempts: 3
maxAttempts无法表达重试行为是基于用同一个endpoint重试还是lb中再select一个重试

2020-10-27 10:20 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/governance-demo/consumer/src/main/resources/application.yaml
> +  retry:
retry是容错发生时的技术手段，不该是治理类型，容错才是治理类型

2020-10-27 10:23 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/governance-demo/consumer/src/main/resources/application.yaml
> +  retry:
可能需要在LB中重新进行select

配置项，retryOnSame, retryOnNext

2020-10-27 10:31 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/governance-demo/consumer/src/main/resources/application.yaml
> +  retry:
配置项规划就这样，可以先支持attempts，改下治理类型

2020-10-27 11:19 UTC, GuoYL123 commented on spring-cloud-huawei-sample/governance-demo/consumer/src/main/resources/application.yaml
> +      maxAttempts: 3
目前是这样设计
```yaml
retry:
  onsame: true/false
  maxAttempts: 3
```
当前逻辑：
onsame关闭(默认关闭)，尽量选择不同实例(是尽量，如果没有其他实例，也会选择请求过的势力)；
onsame开启，会选择同一实例重试。

2020-10-27 11:29 UTC, GuoYL123 commented on spring-cloud-huawei-sample/governance-demo/consumer/src/main/resources/application.yaml
> +  retry:
感觉广义上'重试'的概念更容易接受，不管是sentinel还是resilience4j的描述都是重试。
servicecomb目前的容错的全部内容其实就是重试，还有理解成本，感觉还不如直接叫重试。

2020-10-28 01:09 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/governance-demo/consumer/src/main/resources/application.yaml
> +  retry:
好

2020-10-28 01:10 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/governance-demo/consumer/src/main/resources/application.yaml
> +      maxAttempts: 3
maxAttempts 简化为attempts

2020-10-28 08:51 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/handler/CircuitBreakerHandler.java
> +          .slidingWindowSize(policy.getSlidingWindowSize())
那么如何区分单位呢

2020-10-28 08:53 UTC, develpoerX approved these changes

2020-10-28 08:58 UTC, develpoerX commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/handler/CircuitBreakerHandler.java
> +          .slowCallRateThreshold(policy.getSlowCallRateThreshold())
I noticed that some notes are in Chinese and some are in English. Is it necessary to unify the language of description?

2020-10-28 09:11 UTC, GuoYL123 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/handler/CircuitBreakerHandler.java
> +          .slidingWindowSize(policy.getSlidingWindowSize())
resilience4j定死的，只能是秒

2020-10-28 09:15 UTC, GuoYL123 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/handler/CircuitBreakerHandler.java
> +          .slidingWindowSize(policy.getSlidingWindowSize())
通过slidingWindowType 来确定

2020-10-28 10:46 UTC, tianxiaoliang requested changes

2020-10-28 10:46 UTC, tianxiaoliang commented on spring-cloud-huawei-sample/governance-demo/provider/src/main/resources/application.yaml
> +      minimumNumberOfCalls: 2
考虑一个最小化配置吧，不要过多暴露太多东西，只要有以下场景定义能力就行：

在一个x的时间窗内，收到大于n次请求，他们的错误率达到百分之y，则触发熔断

除了这三个参数其他一律先不要支持

2020-10-28 10:47 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/handler/CircuitBreakerHandler.java
> +          .slidingWindowSize(policy.getSlidingWindowSize())
只需要暴露秒的能力，不要暴露次数

2020-10-29 03:23 UTC, tianxiaoliang approved these changes

2020-10-29 06:31 UTC, merged