multiple match / add group
huaweicloud/spring-cloud-huawei pull request #293
Opened 2020-11-13 09:02 UTC by GuoYL123

2020-11-24 08:27 UTC, tianxiaoliang requested changes

2020-11-24 08:27 UTC, tianxiaoliang commented on spring-cloud-huawei-governance/README.md
>    match:
matchGroup

2020-11-25 02:24 UTC, AngLi2 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/policy/AbstractPolicy.java
> +    for (String string : strings) {
不建议用关键字 string 当变量名，且此处可以直接strs.stream().anyMatch(str -> rules.getMatch().contains(str));

2020-11-25 03:35 UTC, GuoYL123 commented on spring-cloud-huawei-governance/README.md
>    match:
done

2020-11-25 03:35 UTC, GuoYL123 commented on spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/policy/AbstractPolicy.java
> +    for (String string : strings) {
done

2020-11-25 10:01 UTC, merged