register service when retry register / change heartbeat url
huaweicloud/spring-cloud-huawei pull request #295
Opened 2020-11-16 02:49 UTC by GuoYL123

2020-11-16 08:39 UTC, liubao68 commented
PR没有对应的 issue 编号

2020-11-16 08:45 UTC, liubao68 commented on spring-cloud-huawei-servicecomb-discovery/src/test/java/com/huaweicloud/servicecomb/discovery/registry/HeartbeatSchedulerTest.java
> +    HeartbeatScheduler heartbeatScheduler = new HeartbeatScheduler(serviceCombDiscoveryProperties, serviceCombClient);
这个测试用例没有任何有效的检查，建议删除。

2020-11-16 08:46 UTC, liubao68 commented on spring-cloud-huawei-servicecomb-discovery/src/test/java/com/huaweicloud/servicecomb/discovery/client/ServiceCombClientTest.java
> +    serviceCombClient.heartbeat("1", "2");
这个类的测试用例没有任何有效检查。

2020-11-18 10:11 UTC, tianxiaoliang requested changes

2020-11-18 10:11 UTC, tianxiaoliang commented on spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
> +        if (serviceCombSwaggerHandler != null) {
if 和if else长得一样

2020-11-18 10:22 UTC, tianxiaoliang commented on spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
> +        loopRegister(microservice);
这里无限重试下去？何时终止

2020-11-19 01:11 UTC, GuoYL123 commented on spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
> +        loopRegister(microservice);
实例注册成功就会终止，如果没成功就一直重试，因为是异步执行，所以不阻塞主线程

2020-11-19 01:32 UTC, GuoYL123 commented on spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
> +        if (serviceCombSwaggerHandler != null) {
实际不在同一层级，逻辑没问题；
但确实不易读，可以优化下

2020-11-19 01:33 UTC, GuoYL123 commented on spring-cloud-huawei-servicecomb-discovery/src/test/java/com/huaweicloud/servicecomb/discovery/client/ServiceCombClientTest.java
> +    serviceCombClient.heartbeat("1", "2");
增加check

2020-11-19 01:38 UTC, tianxiaoliang commented on spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
> +        loopRegister(microservice);
嗯重试要做退让算法保护

2020-11-19 08:36 UTC, tianxiaoliang approved these changes

2020-11-19 08:36 UTC, merged