[WIP][#311]基于流量特征标记的治理功能
huaweicloud/spring-cloud-huawei pull request #312
Opened 2020-12-18 04:02 UTC by liubao68

2020-12-18 06:32 UTC, GuoYL123 reviewed
把@Bean替换成@Component似乎不是一个好的实践，参考同类spring cloud开源软件以及spring cloud huawei之前的风格@Bean是一种应用更广泛并可以灵活控制bean注入的方法

2020-12-18 06:35 UTC, GuoYL123 reviewed
似乎改变了响应动态配置的方式，但目前没看到EventManager.post被调用的地方？为什么不采用之前的事件机制

2020-12-18 06:35 UTC, GuoYL123 reviewed
为什么要改变moudule名称？

2020-12-22 02:26 UTC, GuoYL123 requested changes

2020-12-22 13:50 UTC, liubao68 commented on governance/src/main/java/com/huaweicloud/governance/handler/AbstractGovHandler.java
> +}
fixed in [#311]基于流量特征标记的治理功能：配置变更逻辑处理

2020-12-23 01:47 UTC, GuoYL123 commented on governance/src/main/java/com/huaweicloud/governance/util/MD5Util.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(MD5Util.class);
这个类已经没用了

2020-12-23 01:47 UTC, GuoYL123 commented on governance/src/main/java/com/huaweicloud/governance/properties/GovProperties.java
> +      // recursively get EnumerablePropertySource
传一个Set作为参数不如直接返回一个Set

2020-12-23 03:02 UTC, liubao68 commented on governance/src/main/java/com/huaweicloud/governance/properties/GovProperties.java
> +      // recursively get EnumerablePropertySource
这是一个递归调用的逻辑，使用传参的方式比较简洁。

2020-12-23 03:03 UTC, liubao68 commented on governance/src/main/java/com/huaweicloud/governance/util/MD5Util.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(MD5Util.class);
OK。删除。

2020-12-28 07:06 UTC, merged