fix governance bug and add check for unsupported operator
huaweicloud/spring-cloud-huawei pull request #334
Opened 2021-01-22 02:19 UTC by GuoYL123

2021-01-22 10:08 UTC, liubao68 reviewed
使用正确的issue ID，比如： https://github.com/huaweicloud/spring-cloud-huawei/issues/335

消息格式： [#335]xxx

2021-01-22 10:08 UTC, liubao68 commented on governance/src/main/java/org/apache/servicecomb/governance/marker/RequestProcessor.java
> +      MatchOperator operator = operatorMap.get(entry.getKey() + OPERATOR_SUFFIX);
这个issue改了3个错误场景，建议增加3个测试用例

2021-01-22 10:09 UTC, liubao68 requested changes
fix the problems mentioned in commit message and test cases

2021-01-25 03:17 UTC, GuoYL123 commented on governance/src/main/java/org/apache/servicecomb/governance/marker/RequestProcessor.java
> +      MatchOperator operator = operatorMap.get(entry.getKey() + OPERATOR_SUFFIX);
添加了单元测试

2021-01-25 08:10 UTC, liubao68 approved these changes

2021-01-25 08:11 UTC, merged